"""
╔══════════════════════════════════════════════════════════════════════════════╗
║              SVEIR MALL SIMULATION  —  ENGINE                               ║
║                                                                              ║
║  DO NOT EDIT THIS FILE.                                                      ║
║  Edit workshop.py to define interventions.                                   ║
║  Edit model.py to change disease parameters.                                 ║
╚══════════════════════════════════════════════════════════════════════════════╝
"""

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.animation import FuncAnimation
from matplotlib.lines import Line2D
from matplotlib.colors import TwoSlopeNorm

# ── ODE parameters (from model.py) ───────────────────────────────────────────
from model import BETA, NU, EPSILON, SIGMA, GAMMA, SPATIAL_FACTOR, E_SEED, solve_ode

# ── Workshop hooks (from workshop.py) ────────────────────────────────────────
# Wrapped in try/except so missing or broken functions don't crash the sim.
try:
    from workshop import zone_risk as _zone_risk
except Exception:
    _zone_risk = None

try:
    from workshop import movement_policy as _movement_policy
except Exception:
    _movement_policy = None

try:
    from workshop import transmission_modifier as _transmission_modifier
except Exception:
    _transmission_modifier = None

try:
    from workshop import policy_label as _policy_label
except Exception:
    _policy_label = None

def zone_risk(x, y):
    try:
        return float(_zone_risk(x, y)) if _zone_risk else 1.0
    except Exception:
        return 1.0

def movement_policy(state, x, y, day, counts, N):
    try:
        return _movement_policy(state, x, y, day, counts, N) if _movement_policy else None
    except Exception:
        return None

def transmission_modifier(sus_state, sx, sy, ix, iy, base_prob, day, counts, N):
    try:
        return float(_transmission_modifier(sus_state, sx, sy, ix, iy,
                                            base_prob, day, counts, N)
                     ) if _transmission_modifier else base_prob
    except Exception:
        return base_prob

def policy_label(day, counts, N):
    try:
        return str(_policy_label(day, counts, N)) if _policy_label else ''
    except Exception:
        return ''


# ── States ────────────────────────────────────────────────────────────────────
S, V, E, I, R = 0, 1, 2, 3, 4
COLORS = {S: '#4A90D9', V: '#9B59B6', E: '#F5A623', I: '#E74C3C', R: '#2ECC71'}
LABELS = {S: 'Susceptible', V: 'Vaccinated', E: 'Exposed', I: 'Infected', R: 'Recovered'}
SIZES  = {S: 28, V: 28, E: 36, I: 44, R: 28}

# ── Simulation constants ──────────────────────────────────────────────────────
N          = 250
MALL_W     = 120
MALL_H     = 80
SPEED      = 0.55
NOISE      = 0.18
INF_RADIUS = 2.8
VAX_RATE   = 0.25
FPS        = 60       # ms per animation frame
FPD        = 10       # simulation frames per in-model day
SIM_DAYS   = 80
FRAMES     = SIM_DAYS * FPD

# ── Agent parameters derived from ODE ────────────────────────────────────────
INCUBATION = max(1, int(FPD / SIGMA))
RECOVERY   = max(1, int(FPD / GAMMA))
VAX_PROT   = 1.0 - EPSILON
TRANS_PROB = BETA * MALL_W * MALL_H / (np.pi * INF_RADIUS**2 * N * FPD)

# ── Pre-run ODE for overlay ───────────────────────────────────────────────────
ode_t, ode_S, ode_V, ode_E, ode_I, ode_R = solve_ode(
    N_pop=N, vax_fraction=VAX_RATE, n_infected=1,
    days=SIM_DAYS, e_seed=E_SEED
)

# ── Mall layout ───────────────────────────────────────────────────────────────
STORES = [
    (2,   4,  16, 14, "ZARA"),   (21,  4, 16, 14, "H&M"),
    (40,  4,  16, 14, "NIKE"),   (59,  4, 16, 14, "APPLE"),
    (78,  4,  16, 14, "GUCCI"),  (98,  4, 16, 14, "BOOKS"),
    (2,  62,  16, 14, "CINEMA"), (21, 62, 16, 14, "GYM"),
    (40, 62,  16, 14, "GAMES"),  (59, 62, 16, 14, "SPORT"),
    (78, 62,  16, 14, "TOYS"),   (98, 62, 16, 14, "TECH"),
    (2,  30,  12, 20, "CAFE"),   (106, 30, 12, 20, "SPA"),
]
FOOD_CX, FOOD_CY, FOOD_R = MALL_W / 2, MALL_H / 2, 9


# ── Agent class ───────────────────────────────────────────────────────────────
class Agent:
    def __init__(self, idx):
        self.x = np.random.uniform(5, MALL_W - 5)
        self.y = np.random.uniform(5, MALL_H - 5)
        angle  = np.random.uniform(0, 2 * np.pi)
        self.vx = SPEED * np.cos(angle)
        self.vy = SPEED * np.sin(angle)
        self.state = V if idx < int(VAX_RATE * N) else S
        self.timer = 0
        self.dest_x = np.random.uniform(10, MALL_W - 10)
        self.dest_y = np.random.uniform(10, MALL_H - 10)
        self.dest_timer = 0

    def move(self, day, counts):
        # Ask workshop if movement should be overridden
        self.dest_timer += 1
        override = movement_policy(self.state, self.x, self.y, day, counts, N)
        if override is not None:
            ox, oy = override
            self.dest_x = float(np.clip(ox, 0, MALL_W))
            self.dest_y = float(np.clip(oy, 0, MALL_H))
            self.dest_timer = 0
        elif self.dest_timer > np.random.randint(60, 180):
            self.dest_x = np.random.uniform(8, MALL_W - 8)
            self.dest_y = np.random.uniform(8, MALL_H - 8)
            self.dest_timer = 0

        dx = self.dest_x - self.x
        dy = self.dest_y - self.y
        dist = np.hypot(dx, dy) + 1e-6
        self.vx += (dx / dist) * 0.12 + np.random.normal(0, NOISE)
        self.vy += (dy / dist) * 0.12 + np.random.normal(0, NOISE)

        spd = np.hypot(self.vx, self.vy)
        if spd > SPEED:
            self.vx = self.vx / spd * SPEED
            self.vy = self.vy / spd * SPEED

        self.x = float(np.clip(self.x + self.vx, 0, MALL_W))
        self.y = float(np.clip(self.y + self.vy, 0, MALL_H))

        if self.x <= 0 or self.x >= MALL_W:
            self.vx *= -1
        if self.y <= 0 or self.y >= MALL_H:
            self.vy *= -1

    def tick(self):
        if self.state == E:
            self.timer += 1
            if self.timer >= INCUBATION:
                self.state = I
                self.timer = 0
        elif self.state == I:
            self.timer += 1
            if self.timer >= RECOVERY:
                self.state = R


# ── Initialize agents ─────────────────────────────────────────────────────────
agents = [Agent(i) for i in range(N)]
agents[0].state = I
agents[0].x = FOOD_CX + np.random.uniform(-2, 2)
agents[0].y = FOOD_CY + np.random.uniform(-2, 2)

history = {s: [] for s in [S, V, E, I, R]}

# ── Pre-compute zone-risk heatmap ─────────────────────────────────────────────
_hm_xs = np.linspace(0, MALL_W, 80)
_hm_ys = np.linspace(0, MALL_H, 54)
_HMX, _HMY = np.meshgrid(_hm_xs, _hm_ys)
_risk_grid = np.vectorize(zone_risk)(_HMX, _HMY)
_risk_uniform = np.allclose(_risk_grid, 1.0)   # skip heatmap if all 1.0


# ── Figure layout ─────────────────────────────────────────────────────────────
fig = plt.figure(figsize=(17, 8.5), facecolor='#0d0d1a')
fig.suptitle("Mall Infection Spread Simulator  •  SVEIR Model  •  workshop.py active",
             color='white', fontsize=13, fontweight='bold', y=0.98)

ax_mall = fig.add_axes([0.01, 0.04, 0.60, 0.90])
ax_mall.set_facecolor('#1b1b2f')
ax_mall.set_xlim(-1, MALL_W + 1)
ax_mall.set_ylim(-1, MALL_H + 1)
ax_mall.set_aspect('equal')
ax_mall.axis('off')

# Floor tiles
for gx in range(0, int(MALL_W) + 1, 10):
    ax_mall.axvline(gx, color='#252540', lw=0.4, zorder=0)
for gy in range(0, int(MALL_H) + 1, 10):
    ax_mall.axhline(gy, color='#252540', lw=0.4, zorder=0)

# Zone-risk heatmap (shows zone_risk() output as a colour overlay)
_norm = TwoSlopeNorm(vmin=0.5, vcenter=1.0, vmax=3.0)
heatmap_img = ax_mall.imshow(
    _risk_grid,
    extent=[0, MALL_W, 0, MALL_H],
    origin='lower', aspect='auto',
    cmap='RdYlBu_r', norm=_norm,
    alpha=0.0 if _risk_uniform else 0.30,
    zorder=1
)

# Mall border
ax_mall.add_patch(patches.FancyBboxPatch(
    (0, 0), MALL_W, MALL_H,
    boxstyle="round,pad=0.5", linewidth=2,
    edgecolor='#5555aa', facecolor='none', zorder=3
))

# Stores
for (sx, sy, sw, sh, label) in STORES:
    ax_mall.add_patch(patches.FancyBboxPatch(
        (sx, sy), sw, sh,
        boxstyle="round,pad=0.3", linewidth=1,
        edgecolor='#6060a0', facecolor='#14143a', zorder=4
    ))
    ax_mall.text(sx + sw/2, sy + sh/2, label, color='#8888cc',
                 ha='center', va='center', fontsize=6, fontweight='bold', zorder=5)

# Food court
ax_mall.add_patch(plt.Circle((FOOD_CX, FOOD_CY), FOOD_R + 1.5, color='#1e1e45', zorder=4))
ax_mall.add_patch(plt.Circle((FOOD_CX, FOOD_CY), FOOD_R,
    fill=False, edgecolor='#7070cc', lw=1.8, linestyle='--', zorder=5))
ax_mall.text(FOOD_CX, FOOD_CY, "FOOD\nCOURT", color='#9999dd',
             ha='center', va='center', fontsize=7, fontweight='bold', zorder=6)

# Infection radius ring
inf_ring = plt.Circle((FOOD_CX, FOOD_CY), INF_RADIUS,
    fill=False, edgecolor='#E74C3C', lw=0.7, alpha=0.4, zorder=6)
ax_mall.add_patch(inf_ring)

# Agent scatter
scatter = ax_mall.scatter([], [], s=30, zorder=7, linewidths=0.4, edgecolors='none')

# Overlays
day_text = ax_mall.text(1, MALL_H - 1.5, '', color='white',
                        fontsize=12, fontweight='bold', zorder=8, va='top')
re_text  = ax_mall.text(1, MALL_H - 8, '', color='#aaaaff',
                        fontsize=9, zorder=8, va='top')
inf_text = ax_mall.text(MALL_W - 1, MALL_H - 1.5, '', color='#E74C3C',
                        fontsize=11, fontweight='bold', zorder=8, va='top', ha='right')

# Policy banner (shown when policy_label() returns a non-empty string)
policy_box = ax_mall.text(
    MALL_W / 2, MALL_H / 2 + FOOD_R + 5, '',
    color='white', fontsize=11, fontweight='bold',
    ha='center', va='bottom', zorder=9,
    bbox=dict(boxstyle='round,pad=0.4', facecolor='#cc2200',
              edgecolor='#ff4422', alpha=0.0)
)

# Heatmap legend note
if not _risk_uniform:
    ax_mall.text(MALL_W - 1, 1, 'risk heatmap: blue=low  red=high',
                 color='#666688', fontsize=6, ha='right', va='bottom', zorder=8)

# Agent legend
legend_elements = [
    Line2D([0], [0], marker='o', color='w',
           markerfacecolor=COLORS[s], markersize=8, label=LABELS[s], linestyle='None')
    for s in [S, V, E, I, R]
]
ax_mall.legend(handles=legend_elements, loc='lower right',
               facecolor='#1b1b2f', labelcolor='white',
               edgecolor='#5555aa', fontsize=8)


# ── Time-series chart ─────────────────────────────────────────────────────────
ax_ts = fig.add_axes([0.63, 0.52, 0.35, 0.42])
ax_ts.set_facecolor('#0d0d1a')
ax_ts.set_title(f'ODE (β×{SPATIAL_FACTOR}, E₀+{E_SEED})  vs  Agent Simulation',
                color='white', fontsize=10, pad=6)
ax_ts.tick_params(colors='#aaaaaa', labelsize=8)
for sp in ax_ts.spines.values():
    sp.set_color('#333355')
ax_ts.set_xlabel('Day', color='#aaaaaa', fontsize=8)
ax_ts.set_ylabel('Count', color='#aaaaaa', fontsize=8)
ax_ts.set_xlim(0, SIM_DAYS)
ax_ts.set_ylim(0, N)

ode_arrays = {S: ode_S, V: ode_V, E: ode_E, I: ode_I, R: ode_R}
for state in [S, V, E, I, R]:
    ax_ts.plot(ode_t, ode_arrays[state], color=COLORS[state],
               lw=1.2, linestyle='--', alpha=0.5, zorder=1)

ts_lines = {}
for state in [S, V, E, I, R]:
    ln, = ax_ts.plot([], [], color=COLORS[state], lw=1.8, label=LABELS[state], zorder=2)
    ts_lines[state] = ln

legend_handles = [
    Line2D([0], [0], color=COLORS[s], lw=1.8, label=LABELS[s]) for s in [S, V, E, I, R]
]
legend_handles.append(
    Line2D([0], [0], color='white', lw=1.2, linestyle='--', alpha=0.6, label='ODE prediction')
)
ax_ts.legend(handles=legend_handles, loc='upper right', fontsize=6.5,
             facecolor='#0d0d1a', labelcolor='white', edgecolor='#333355')

# ── Bar chart ─────────────────────────────────────────────────────────────────
ax_bar = fig.add_axes([0.63, 0.06, 0.35, 0.38])
ax_bar.set_facecolor('#0d0d1a')
ax_bar.set_title('Current Status', color='white', fontsize=10, pad=6)
ax_bar.tick_params(colors='#aaaaaa', labelsize=8)
ax_bar.tick_params(axis='x', rotation=25)
for sp in ax_bar.spines.values():
    sp.set_color('#333355')
ax_bar.set_ylim(0, N)
ax_bar.set_ylabel('Count', color='#aaaaaa', fontsize=8)

bar_states = [S, V, E, I, R]
bars = ax_bar.bar(
    [LABELS[s] for s in bar_states],
    [N * (1 - VAX_RATE), N * VAX_RATE, 0, 1, 0],
    color=[COLORS[s] for s in bar_states],
    edgecolor='none', width=0.6
)
bar_vals = [
    ax_bar.text(bar.get_x() + bar.get_width()/2, 0, '',
                ha='center', va='bottom', color='white', fontsize=8, fontweight='bold')
    for bar in bars
]


# ── Animation update ──────────────────────────────────────────────────────────
frame_num = [0]

def update(frame):
    frame_num[0] += 1
    day = frame_num[0] / FPD

    pos        = np.array([[a.x, a.y] for a in agents])
    states_arr = np.array([a.state   for a in agents])
    counts     = {s: int(np.sum(states_arr == s)) for s in [S, V, E, I, R]}

    infected_pos = pos[states_arr == I]

    for i, agent in enumerate(agents):
        # S → V ongoing vaccination (matches ODE nu*S term)
        if agent.state == S and np.random.random() < NU / FPD:
            agent.state = V
            agent.move(day, counts)
            continue

        # Infection check
        if agent.state in (S, V) and len(infected_pos) > 0:
            dists = np.hypot(pos[i, 0] - infected_pos[:, 0],
                             pos[i, 1] - infected_pos[:, 1])
            if np.any(dists < INF_RADIUS):
                # Nearest infected agent (for position info passed to hook)
                nearest = infected_pos[np.argmin(dists)]
                # Base probability: zone risk × vaccine protection
                base = TRANS_PROB * zone_risk(agent.x, agent.y)
                if agent.state == V:
                    base *= (1.0 - VAX_PROT)
                # Workshop transmission modifier
                prob = transmission_modifier(
                    agent.state, agent.x, agent.y,
                    nearest[0], nearest[1],
                    base, day, counts, N
                )
                if np.random.random() < float(np.clip(prob, 0.0, 1.0)):
                    agent.state = E

        agent.tick()
        agent.move(day, counts)

    # ── Scatter update
    xs     = [a.x for a in agents]
    ys     = [a.y for a in agents]
    colors = [COLORS[a.state] for a in agents]
    sizes  = [SIZES[a.state]  for a in agents]
    scatter.set_offsets(np.c_[xs, ys])
    scatter.set_color(colors)
    scatter.set_sizes(sizes)

    # Re-read counts from updated states
    states_arr = np.array([a.state for a in agents])
    counts = {s: int(np.sum(states_arr == s)) for s in [S, V, E, I, R]}
    for s in [S, V, E, I, R]:
        history[s].append(counts[s])

    # ── Infection-radius ring follows lead infected agent
    inf_agents = [a for a in agents if a.state == I]
    if inf_agents:
        lead = inf_agents[0]
        inf_ring.center = (lead.x, lead.y)
        inf_ring.set_visible(True)
    else:
        inf_ring.set_visible(False)

    # ── Text overlays
    effective_beta = BETA * SPATIAL_FACTOR
    Re = (effective_beta / GAMMA) * (counts[S] / N)
    day_text.set_text(f'Day {int(day)}')
    re_text.set_text(f'Rₑ = {Re:.2f}')
    re_text.set_color('#ff6666' if Re > 1 else '#66ff66')
    inf_text.set_text(f'Active: {counts[I] + counts[E]}')

    # ── Policy banner
    label = policy_label(day, counts, N)
    policy_box.set_text(label)
    policy_box.get_bbox_patch().set_alpha(0.85 if label else 0.0)

    # ── Time-series
    x_data = [f / FPD for f in range(len(history[S]))]
    for s in [S, V, E, I, R]:
        ts_lines[s].set_data(x_data, history[s])

    # ── Bar chart
    for bar, bval, s in zip(bars, bar_vals, bar_states):
        h = counts[s]
        bar.set_height(h)
        bval.set_text(str(h))
        bval.set_y(h + 1)

    return ([scatter, inf_ring, day_text, re_text, inf_text, policy_box]
            + list(ts_lines.values()) + list(bars) + bar_vals)


ani = FuncAnimation(fig, update, frames=FRAMES, interval=FPS, blit=False)
plt.show()
